// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node -r tsconfig-paths/register prisma/seed.ts',
  },
  datasource: {
    // El CLI (migrate/seed) usa esta url. En Supabase las migraciones requieren una
    // conexión DIRECTA (no el pooler de transacciones). Por eso preferimos DIRECT_URL
    // si está seteado (prod), con fallback a DATABASE_URL (local = conexión directa a
    // :54322, no hay pooler). El runtime (PrismaPg adapter en prisma.service.ts) usa
    // siempre DATABASE_URL (en prod = pooler :6543).
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
