/**
 * Imports error_catalog.jsonl generated by innova-ai-engine into the ErrorTag table.
 * Idempotent: upserts by `code`. Validates schema before inserting.
 *
 * Usage (note: --input uses '='):
 *   pnpm import:catalog --input=../innova-ai-engine/out/error_catalog.jsonl [--dry-run]
 */
import 'dotenv/config';
import * as fs from 'fs';
import * as readline from 'readline';

import { PrismaPg } from '@prisma/adapter-pg';
import {
  ErrorSeverity,
  ErrorSource,
  ErrorStatus,
  PrismaClient,
} from '@prisma/client';
import { z } from 'zod';

const args = process.argv.slice(2);
const inputArg = args.find((a) => a.startsWith('--input='));
const dryRunFlag = args.includes('--dry-run');
const activateFlag = args.includes('--activate');

if (!inputArg) {
  console.error(
    'Usage: pnpm tsx scripts/import-error-catalog.ts --input=<path> [--dry-run] [--activate]',
  );
  process.exit(1);
}

const inputPath = inputArg.split('=')[1];

// Zod schema for a single ErrorTag catalog entry
const CatalogEntrySchema = z.object({
  code: z
    .string()
    .regex(
      /^[A-Z][A-Z0-9]*_[A-Z][A-Z0-9]*_[A-Z][A-Z0-9_]*$/,
      'code must match <DOMAIN>_<SUBDOMAIN>_<NAME> pattern',
    ),
  name: z.string().min(1),
  description: z.string().min(1),
  domain_code: z.string().min(1),
  subdomain_code: z.string().min(1),
  severity: z.nativeEnum(ErrorSeverity),
  source: z.nativeEnum(ErrorSource).default(ErrorSource.LLM_GENERATED),
  status: z.nativeEnum(ErrorStatus).default(ErrorStatus.DRAFT),
  applicable_grades: z
    .array(z.number().int().min(1).max(12))
    .optional()
    .default([]),
  evidence_required: z.array(z.string()).optional().default([]),
  diagnostic_hint: z.string().optional(),
  remediation: z.string().optional(),
  references: z.array(z.string()).optional().default([]),
  topic_scope: z.string().optional(),
});

type CatalogEntry = z.infer<typeof CatalogEntrySchema>;

interface Stats {
  total: number;
  loaded: number;
  duplicates: number;
  rejected: number;
  draftCount: number;
  activeCount: number;
  byDomain: Record<string, number>;
}

const adapter = new PrismaPg({
  connectionString: process.env['DATABASE_URL']!,
});
const prisma = new PrismaClient({ adapter });

async function main(): Promise<void> {
  if (!fs.existsSync(inputPath)) {
    console.error(`❌ Input file not found: ${inputPath}`);
    process.exit(1);
  }

  // Pre-load domain codes for validation
  const domains = await prisma.domain.findMany({
    select: { id: true, code: true },
  });
  const domainMap = new Map(domains.map((d) => [d.code, d.id]));

  if (domainMap.size === 0) {
    console.error(
      '❌ No domains found in DB — run seeds (prisma db seed) first.',
    );
    process.exit(1);
  }

  const stats: Stats = {
    total: 0,
    loaded: 0,
    duplicates: 0,
    rejected: 0,
    draftCount: 0,
    activeCount: 0,
    byDomain: {},
  };

  const errors: Array<{ line: number; code: string; reason: string }> = [];
  const rl = readline.createInterface({
    input: fs.createReadStream(inputPath),
  });

  let lineNum = 0;
  const entries: Array<{ entry: CatalogEntry; domainId: string }> = [];

  for await (const raw of rl) {
    lineNum++;
    const trimmed = raw.trim();
    if (!trimmed || trimmed.startsWith('//')) continue;

    stats.total++;

    let parsed: unknown;
    try {
      parsed = JSON.parse(trimmed);
    } catch {
      errors.push({ line: lineNum, code: '?', reason: 'Invalid JSON' });
      stats.rejected++;
      continue;
    }

    const result = CatalogEntrySchema.safeParse(parsed);
    if (!result.success) {
      const code =
        ((parsed as Record<string, unknown>)['code'] as string) ?? '?';
      errors.push({ line: lineNum, code, reason: result.error.message });
      stats.rejected++;
      continue;
    }

    const entry = result.data;
    const domainId = domainMap.get(entry.domain_code);
    if (domainId === undefined) {
      errors.push({
        line: lineNum,
        code: entry.code,
        reason: `Unknown domain_code: ${entry.domain_code}`,
      });
      stats.rejected++;
      continue;
    }

    entries.push({ entry, domainId });
  }

  console.log(
    `\n📋 Parsed ${stats.total} lines → ${entries.length} valid, ${stats.rejected} rejected`,
  );

  if (errors.length > 0 && stats.rejected > 0) {
    console.log('\n⚠️  Rejected entries (first 10):');
    errors.slice(0, 10).forEach(({ line, code, reason }) => {
      console.log(`   Line ${line} [${code}]: ${reason}`);
    });
  }

  if (dryRunFlag) {
    console.log('\n🔍 Dry run — no writes performed.');
    return;
  }

  // Upsert in batches of 50
  const BATCH_SIZE = 50;
  for (let i = 0; i < entries.length; i += BATCH_SIZE) {
    const batch = entries.slice(i, i + BATCH_SIZE);
    await Promise.all(
      batch.map(async ({ entry, domainId }) => {
        const data = {
          name: entry.name,
          description: entry.description,
          domainId,
          subdomainCode: entry.subdomain_code,
          source: entry.source,
          status: entry.status,
          severity: entry.severity,
          applicableGrades: entry.applicable_grades,
          evidenceRequired: entry.evidence_required,
          diagnosticHint: entry.diagnostic_hint ?? null,
          remediation: entry.remediation ?? null,
          references: entry.references,
          topicScope: entry.topic_scope ?? null,
        };

        const effectiveStatus = activateFlag ? ErrorStatus.ACTIVE : entry.status;
        const effectiveData = { ...data, status: effectiveStatus };

        const existing = await prisma.errorTag.findUnique({
          where: { code: entry.code },
        });
        if (existing) {
          if (activateFlag && existing.status === ErrorStatus.DRAFT) {
            await prisma.errorTag.update({
              where: { code: entry.code },
              data: { status: ErrorStatus.ACTIVE },
            });
            stats.activeCount++;
            stats.byDomain[entry.domain_code] =
              (stats.byDomain[entry.domain_code] ?? 0) + 1;
          } else {
            stats.duplicates++;
          }
          return;
        }

        await prisma.errorTag.create({ data: { code: entry.code, ...effectiveData } });
        stats.loaded++;
        stats.byDomain[entry.domain_code] =
          (stats.byDomain[entry.domain_code] ?? 0) + 1;
        if (effectiveStatus === ErrorStatus.DRAFT) stats.draftCount++;
        else stats.activeCount++;
      }),
    );
  }

  console.log(`\n✅ Import complete${activateFlag ? ' (--activate: all set to ACTIVE)' : ''}:`);
  console.log(`   Loaded: ${stats.loaded}`);
  console.log(`   Duplicates skipped: ${stats.duplicates}`);
  console.log(`   Rejected: ${stats.rejected}`);
  console.log(`   ACTIVE: ${stats.activeCount} | DRAFT: ${stats.draftCount}`);
  console.log('\n   By domain:');
  Object.entries(stats.byDomain)
    .sort(([, a], [, b]) => b - a)
    .forEach(([domain, count]) => console.log(`   ${domain}: ${count}`));
}

main()
  .catch((e) => {
    console.error('❌ Import failed:', e);
    process.exit(1);
  })
  .finally(() => void prisma.$disconnect());
